name: CI workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the runner environment, can also use 'container' directly
    container:
      image: python:3.9-slim  # Specify the container image you want to use here
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
